version: "3"
services:
    ansible_tower:
        image: ansible_tower
        ports:
            - "8022:22"
        restart: "no"
        volumes:
            - ./inventory:/etc/ansible/
        container_name: "ansible_tower"
        hostname: "ansible_tower"

    starfigther_bajovnick:
        image: bajovnick
        expose:
            - "22"
            - "80"
        restart: "no"
        container_name: "bajovnick"
        hostname: "bajovnick"

